# ruff.toml

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Formatting/linting base settings
line-length = 79
indent-width = 4
target-version = "py313"

[lint]
select = [
            "E",   # All pycodestyle errors
            "F",   # Pyflakes
            "D",   # pydocstyle (docstrings)
            "I",   # Full import sorting (not just I001)
            "UP",  # pyupgrade
        ]
ignore = [
            "D105", # Missing docstring in magic method
            "D107", # Missing docstring in __init__
            "D203", # Conflicts with D213
            "D213", # Conflicts with D203
            "D100", # Missing module docstring
            "D101", # Missing docstring in public class   !!!!!!!!!!!!! TEMP !!!!!!!!!!!!!!!!!!!
            "D102", # Missing docstring in public method  !!!!!!!!!!!!! TEMP !!!!!!!!!!!!!!!!!!!
            "D103", #  !!!!!!!!!!!!! TEMP !!!!!!!!!!!!!!!!!!!
            "D104", # Missing docstring in public package !!!!!!!!!!!!! TEMP !!!!!!!!!!!!!!!!!!!
        ]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"              # use double quotes for strings.
indent-style = "space"              # indent with spaces, rather than tabs.
skip-magic-trailing-comma = false   # respect magic trailing commas.
line-ending = "auto"                # automatically detect the appropriate line ending.
docstring-code-format = true        # Enable auto-formatting of code examples in docstrings.
docstring-code-line-length = "dynamic"
